### ISSUE TITLE
Default Config are not loaded

### ISSUE THREAD

**Issue by piotrkluz** [comfast-dev/comfast-ui#3]
After import comfast-ui in separate project, this config should be loadedas default: 
Expected:
```
cf.timeoutMs: 4000
cf.browser:
  name: chrome
  autoClose: true
  reconnect: false
```

Actually there are missing default `cf.browser.name` at Runtime

**Comment by piotrkluz** [comment]
Fixed in version `0.2.3`. 
Added `referenceConfig.yaml` with all defaults: 
```
cf:
  timeoutMs: 4000
  browser:
    name: chrome
    autoClose: true
    reconnect: false
```
```
